Repository ppc64le-cloud/docker-ce-build, pull requests merged in 2022-08, with the labels that each got.

#45 Improve the paralelized build
  build-docker.sh
Labels: approved, size/M

#46 Add parallelization of building&testing containerd
  build-containerd.sh
Labels: approved

#47 Fix issues of parallelism
  build-containerd.sh
Labels: approved

#48 Improve parallelism
  build-docker.sh
Labels: approved

#49 Use a specific directory for each distro
  build-containerd.sh
Labels: approved

#50 Modify go test timeout
  test-containerd/test_on_powervs.sh
Labels: size/S, approved, lgtm

#51 Add failpoint setup script
  test-containerd/test_on_powervs.sh
Labels: size/XS, approved, lgtm

#53 Fix gotestsum error for the docker packaging tests
  env/env.list
  get-env-containerd.sh
  prow-test-docker.sh
  test-launch.sh
  test.sh
Labels: size/S, approved, lgtm
