Repository ppc64le-cloud/docker-ce-build, pull requests merged in 2022-03, with the labels that each got.

#18 Fix centos 8 build moving to centos stream
  build-docker.sh
  dockerctl.sh
  env/env.list
Labels: size/S, approved, lgtm

#19 Add scripts to test containerd
  test-containerd/instanciate_powervs_vm.sh
  test-containerd/test_on_powervs.sh
Labels: size/L, approved, lgtm

#20 Use the right test file
  test-containerd/instanciate_powervs_vm.sh
Labels: size/XS, approved, lgtm

#21 Fix centOS 8 Stream for containerd
  build-containerd.sh
  build-static.sh
  env/env.list
  get-env-containerd.sh
  test.sh
  test_staging.sh
Labels: size/L, approved, lgtm

#22 Update for containerd 1.4.13 and staging tests
  README.md
  build-containerd.sh
  env/env.list
  prow-test-docker-staging.sh
  test.sh
  test_staging.sh
Labels: size/L, approved, lgtm

#23 Build: docker 20.10.13 and containerd.io v1.5.10 (with runc v1.0.3)
  env/env.list
Labels: size/XS, approved

#24 Fix test staging, add test release and enable copy package to shared COS bucket for CONTAINERD_BUILD="1"
  README.md
  build-containerd.sh
  prow-build-containerd.sh
  prow-test-docker.sh
  push-COS.sh
  test-launch.sh
  test-repo-DEBS/Dockerfile
  test-repo-RPMS/Dockerfile
  test.sh
Labels: size/L, approved, lgtm

#25 Add new settings DISABLE_DISTRO_DISCOVERY, DISABLE_PUSH_COS
  build-docker.sh
  check-tests.sh
  env/env.list
  env/test-release.list
  env/test-staging.list
  get-env.sh
  prow-build-containerd.sh
  prow-test-docker.sh
  push-COS.sh
  test.sh
Labels: size/XL, approved, lgtm

#26 Rename prow-build-containerd.sh -> prow-build-test-containerd.sh
  README.md
  prow-build-test-containerd.sh
Labels: size/XS, approved, lgtm

#27 Update build settings for docker 20.10.14 and containerd 1.5.11
  env/env.list
Labels: size/S, approved

#28 Fix typo on Docker version in env.list
  env/env.list
Labels: approved

#29 Fix side effect with Go version variable
  build-containerd.sh
  env/env.list
Labels: size/XS, approved, lgtm

#31 Change error message in order to check error in text files easily.
  test-containerd/instanciate_powervs_vm.sh
  test-containerd/test_on_powervs.sh
Labels: size/S, approved, lgtm

#33 Remove env/date.list, this file is now created by prow-build-docker.sh
  README.md
  env/date.list
Labels: size/XS, approved, lgtm
