Repository ppc64le-cloud/docker-ce-build, pull requests merged in 2022-05, with the labels that each got.

#37 Build docker 20.10.15 and containerd 1.6.4
  build-containerd.sh
  env/env.list
  test.sh
Labels: approved, size/M, lgtm

#38 Add a summary for push_COS.sh
  push-COS.sh
Labels: size/S, approved, lgtm

#39 Moving to Docker v20.10.16
  env/env.list
Labels: size/XS, approved

#40 2ndTry 20.10.16
  env/env.list
Labels: size/XS, approved

#41 Launch verification of release 20.10.15
  env/test-release.list
Labels: size/XS, approved

#42 Spin test stagging for docker 20.10.15, containerd 1.6.4
  env/test-staging.list
Labels: size/XS, approved

#43 Spin test staging for docker 20.10.15, containerd 1.6.4, 2d attempt
  env/test-staging.list
Labels: size/XS, approved
