Repository ppc64le-cloud/docker-ce-build, pull requests merged in 2022-09, with the labels that each got.

#54 Build docker 20.10.18 and containerd 1.6.8
  build-containerd.sh
  build-docker.sh
  env/env.list
Labels: approved, size/M, lgtm

#56 Dev
  build-docker.sh
  env/env.list
Labels: size/XS, approved

#55 Powervs Memory Increase
  test-containerd/instanciate_powervs_vm.sh
  test-containerd/test_on_powervs.sh
Labels: size/S, approved

#57 Retry build after cluster reboot
  env/env.list
Labels: approved

#58 Fix the static build golang issue dueto buster EOL
  build-static.sh
Labels: approved

#59 Re-build/test now that static build failure fixed
  env/env.list
Labels: approved

#60 Dev
  build-docker.sh
  build-static.sh
Labels: size/XS, approved

#61 Update build-static.sh
  build-static.sh
Labels: approved

#62 Fix buster/bullseye in correct Makefiles
  build-static.sh
Labels: approved

#63 Add more trace
  build-docker.sh
Labels: approved

#64 Search for buster anywhere
  build-static.sh
Labels: approved

#65 Dev
  build-containerd.sh
  build-docker.sh
Labels: approved
