Repository ppc64le-cloud/docker-ce-build, pull requests merged in 2023-05, with the labels that each got.

#122 Build Docker 23.0.5
  env/env.list
Labels: size/XS, approved

#123 Test Docker 23.0.5 in staging
  env/test-staging.list
Labels: size/XS, approved

#124 Retest Docker v23.0.5 in staging
  env/test-staging.list
Labels: approved

#125 Build containerd v1.6.21
  env/env.list
Labels: size/XS, approved

#126 Rebuild containerd v1.6.21
  env/env.list
Labels: approved

#127 Test staging containerd 1.6.21
  env/test-staging.list
Labels: approved

#118 Change network delete function
  test-containerd/instantiate_vm_and_test.sh
Labels: size/S, approved, lgtm

#128 Test staging Docker v23.0.5
  env/test-staging.list
Labels: approved

#129 Retest staging Docker v23.0.5
  env/test-staging.list
Labels: approved

#130 Test release Docker v23.0.5 and containerd v1.6.21
  env/test-release.list
Labels: approved

#131 Build Docker v23.0.6
  env/env.list
Labels: approved

#132 Test staging Docker v23.0.6
  env/test-staging.list
Labels: approved

#133 Test release Docker v23.0.6
  env/test-release.list
Labels: approved

#134 Retest release Docker v23.0.6
  env/test-release.list
Labels: approved

#135 Build Docker v24.0.0-rc2
  env/env.list
Labels: approved

#136 Test staging Docker v24.0.0-rc.2
  env/test-staging.list
Labels: size/XS, approved

#137 Test release Docker v24.0.0-rc.2
  env/test-release.list
Labels: approved

#138 Build Docker v24.0.0-rc.3
  env/env.list
Labels: approved

#139 Build Docker v24.0.0
  env/env.list
Labels: approved

#140 Test staging Docker v24.0.0
  env/test-staging.list
Labels: size/XS, approved

#141 Update OWNERS
  OWNERS
Labels: approved

#142 Retest staging Docker v24.0.0
  env/test-staging.list
Labels: approved

#143 Test release Docker v24.0.0
  env/test-release.list
Labels: approved

#144 Build Docker v24.0.1
  env/env.list
Labels: size/S, approved
