Repository ppc64le-cloud/docker-ce-build, pull requests merged in 2023-04, with the labels that each got.

#94 Wait for instance reboot
  test-containerd/instantiate_vm_and_test.sh
Labels: size/XS, approved

#95 Build Docker 23.0.3
  env/env.list
Labels: size/S, approved

#96 Rebuild due to test failure for centos 7
  env/env.list
Labels: size/XS, approved

#97 Rebuild Docker 23.0.3 and containerd 1.6.20 due to pull API request limit exceeded
  env/env.list
Labels: approved

#98 Test Docker v23.0.3 and containerd v1.6.20 in staging
  env/test-staging.list
Labels: approved

#89 Introduced DOCKER_BUILD env var which when unset will only build
  build-docker.sh
  env/env.list
Labels: size/XS, approved, lgtm

#100 Test Docker v23.0.3 and containerd v.1.6.20 in release
  env/test-release.list
Labels: size/XS, approved

#99 Only perform tests if Docker packages are built and not otherwise.
  build-docker.sh
  prow-build-test-containerd.sh
Labels: size/XS, approved

#101 Build Docker v20.10.24
  env/env.list
Labels: approved

#103 Build Docker v20.10.24 and containerd v.1.6.20
  env/env.list
Labels: approved

#106 Retest Docker 20.10.24 in staging
  env/test-staging.list
Labels: approved

#107 Test Docker v20.10.24 in release
  env/test-release.list
Labels: approved

#108 Retest Docker v20.10.24 in release
  env/test-release.list
Labels: approved

#90 Fix Automatic Pushing of Builds to shared COS bucket
  check-tests.sh
  env/env.list
Labels: size/S, approved, lgtm

#109 Testing PR 90: Fix push COS
  env/env.list
Labels: approved

#105 Avoid job failure caused by networking
  test-containerd/instantiate_vm_and_test.sh
Labels: size/S, approved

#110 Build Docker v23.0.4
  env/env.list
Labels: approved

#112 Test Docker v23.0.4 in staging
  env/test-staging.list
Labels: size/XS, approved

#113 Retest Docker 23.0.4 in staging
  env/test-staging.list
Labels: approved

#114 Retest Docker v23.0.4
  env/test-staging.list
Labels: approved

#115 Retest Docker v23.0.4 in staging
  env/test-staging.list
Labels: approved

#111 Debug ssh
  test-containerd/instantiate_vm_and_test.sh
Labels: size/XS, approved

#116 Test Docker v23.0.4 in release
  env/test-release.list
Labels: approved

#117 Retain VM when SSH fails
  test-containerd/instantiate_vm_and_test.sh
Labels: size/XS, approved

#119 Check for alpine tests only during local tests
  check-tests.sh
Labels: size/XS, approved

#120 Test fixing of automatic push to COS bucket
  env/env.list
Labels: approved
