Repository ppc64le-cloud/docker-ce-build, pull requests merged in 2024-02, with the labels that each got.

#175 Update crun version
  test-containerd/test_on_powervs.sh
Labels: size/XS

#178 Set crun version to pinned version
  test-containerd/test_on_powervs.sh
Labels: size/XS

#167 Create LICENSE
  LICENSE
Labels: size/L, approved

#174 Update static build image reference
  README.md
  build-docker.sh
  env/env.list
  get-env.sh
Labels: size/S, approved

#177 Stop using CONTAINERD_HASH
  build-containerd.sh
  env/env.list
  get-env.sh
Labels: size/S, approved

#179 Build Docker v25.0.3 and containerd v1.6.28
  env/env.list
Labels: approved

#180 Build Docker v25.0.3 and containerd v1.6.28
  env/env.list
Labels: approved

#181 Test release Docker v25.0.3
  env/test-release.list
Labels: size/XS, approved

#176 Upstream CI scripts
  README.md
  upstream-master-ci/build-dev-image.sh
  upstream-master-ci/get-env-ci.sh
  upstream-master-ci/info.sh
  upstream-master-ci/integration-tests.sh
  upstream-master-ci/prow-build-dev-image.sh
  upstream-master-ci/prow-info-docker.sh
  upstream-master-ci/prow-integration-tests.sh
  upstream-master-ci/prow-unit-test-docker.sh
  upstream-master-ci/unit-tests.sh
Labels: size/L, approved

#183 Test release Docker v25.0.3
  env/test-release.list
Labels: approved
