Repository ppc64le-cloud/docker-ce-build, pull requests merged in 2025-04, with the labels that each got.

#272 Docker 28.0.4 and containerd v1.7.26 staging tests
  env/test-staging.list
Labels: approved

#273 Docker 28.0.4 and containerd 1.7.26 staging test re-attempt
  env/test-staging.list
Labels: approved

#271 Update periodic CI script introductory display messages
  upstream-master-ci/prow-build-dev-image.sh
  upstream-master-ci/prow-info-docker.sh
Labels: size/XS, approved

#274 Build containerd v1.7.27
  env/env.list
Labels: approved

#276 Build Docker v28.1.0-rc.1 and containerd1.7.27 (to generate packages …
  env/env.list
Labels: approved

#277 Bump go version to 1.23.0 for containerd testing
  test-containerd/test_on_powervs.sh
Labels: size/XS

#278 Build Docker v28.1.0
  env/env.list
Labels: approved

#279 Remove software-properties-common from Debian test Dockerfiles
  test-DEBS/Dockerfile
  test-repo-DEBS/Dockerfile
Labels: size/XS, approved

#280 Test Docker v28.1.0 and containerd v1.7.27 on release
  env/test-release.list
Labels: approved

#281 Build Docker v28.1.1
  env/env.list
Labels: approved
